### ISSUE TITLE
just dropping the EUPL (NL & ES & EN) into your box

### ISSUE THREAD

**Issue by Zweihorn** [dyne/devuan-sdk#1]
Free to share _code._
Code to share _freedom_

That is a nice motto you have at https://dyne.org/

### EUPL

However, I would like you to [become aware of my recent notion of the EUPL](https://github.com/Zweihorn/Zweihorn_fascicle#open-source-endeavour) which could also meet your requirements, I presume. Naturally, I don't want to lecture anybody and you are free to choose at your sole deliberation. Just sharing my belief for learning and improving.

Furthermore, if this might be an **old ha**t i.e. "_oude koek_" to you, have a good laugh on me and drop this where it belongs.

#### Please let me briefly elaborate:

‘Compatible Licences’ according to Article 5 EUPL are, _including but not limited_ to the two you are using, apparently:
- GNU Lesser General Public Licence (**LGPL**) v. 2.1, v. 3
- Creative Commons Attribution-ShareAlike v. 3.0 Unported (**CC BY-SA** 3.0) for works other than software

Presumably,  you could catch two fishes with one fishing net (i.e. one license), if I am correct.

IMHO this could meet also your organisation's legal requirement as an European **private entity** and apparent NGO in beautiful Amsterdam NL, thus outside U.S. jurisdiction. Furthermore, the Open Source Initiative (OSI) approves of EUPL-1.2 and agrees, that **public domain doesn't exist in Europe.**

#### The EUPL (NL)

- [EUPL-1.2 (NL)](https://joinup.ec.europa.eu/sites/default/files/custom-page/attachment/eupl_v1.2_nl.pdf) as PDF
- [EUPL-1.2 (NL)](https://joinup.ec.europa.eu/sites/default/files/inline-files/EUPL%20v1_2%20NL.txt)
- [EUPL v.1.1 - Inleiding](https://wayback.archive-it.org/12090/20200210204548/https://ec.europa.eu/idabc/servlets/Doc81eb.pdf?id=32013)
- [EUPL v.1.1 - Licentie](https://wayback.archive-it.org/12090/20200210204548/https://ec.europa.eu/idabc/servlets/Doc9285.pdf?id=31988)

#### Why this issue now?

Coincidently, I learned of _dyne.org_ through [Minetest](https://www.minetest.net/) FOSS project by b.m. topic only recently: 
- https://forum.minetest.net/viewtopic.php?p=420281#p420281

Last not least I did find no better entry to you after a brief search as I am intentionally not linked to everyone to enjoy some personal freedom in my private kingdom called privacy.

Hope this helps.

No need for reply, if too much, too soon, or just unwanted. 
However, **any of your views** and **any advice** would be _highly appreciated_.

**Comment by Zweihorn** [comment]
@davinerd - FYI

[Próspero](https://dict.leo.org/spanisch-deutsch/%C2%A1Pr%C3%B3spero) [Año](https://dict.leo.org/spanisch-deutsch/A%C3%B1o) [Nuevo](https://dict.leo.org/spanisch-deutsch/Nuevo)!

The EUPL (ES)

- [EUPL-1.2 (ES)](https://joinup.ec.europa.eu/sites/default/files/custom-page/attachment/eupl_v1.2_es.pdf) as PDF
- [EUPL-1.2 (ES)](https://joinup.ec.europa.eu/sites/default/files/inline-files/EUPL%20v1_2%20ES.txt) as TXT
- [EUPL v.1.1 - Preámbulo](https://wayback.archive-it.org/12090/20200210204548/https://ec.europa.eu/idabc/servlets/Doc6e87.pdf?id=32004)
- [EUPL v.1.1 - Licencia](https://wayback.archive-it.org/12090/20200210204548/https://ec.europa.eu/idabc/servlets/Docb4f4.pdf?id=31980)
- https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12

[Afectuosamente](https://dict.leo.org/spanisch-deutsch/Afectuosamente),
@Zweihorn

**Comment by jaromil** [comment]
Bedankt voor de voorstelling. The devuan-sdk project is archived and not in use anymore. Dyne.org holds trademark and has a stewardship role to the Devuan project, but licensing is intertwined with Debian's and won't change.

**Comment by Zweihorn** [comment]
> Bedankt voor de voorstelling.

@jaromil - THX - Dankeschön - heel erg bedankt!
